openapi: 3.0.3
info:
  title: Usuário API
  version: 1.0.0
  description: API para gerenciar usuários
servers:
  - url: http://localhost:8080/
    description: Servidor local
tags:
  - name: Usuário
    description: Operações relacionadas a usuários
paths:
  /usuarios:
    post:
      tags:
        - Usuário
      summary: Cria um novo usuário
      operationId: criarUsuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuário criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
  /usuarios/{id}:
    get:
      tags:
        - Usuário
      summary: Obtém um usuário por ID
      operationId: obterUsuarioPorId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: long
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '404':
          description: Usuário não encontrado
    put:
      summary: Alterar dados do usuário
      operationId: atualizarUsuario
      tags:
        - Usuário
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: long
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioUpdate'
      responses:
        '200':
          description: Usuário atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioUpdate'
  /usuarios/{id}/senha:
    put:
      summary: Trocar senha do usuário
      operationId: trocarSenhaUsuario
      tags:
        - Usuário
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: long
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrocaSenha'
      responses:
        '200':
          description: Senha alterada
components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: long
          example: 1
        login:
          type: string
          maxLength: 50
          example: leonart
        email:
          type: string
          maxLength: 100
          example: leonart@email.com
        senha:
          type: string
          maxLength: 16
          example: senha123
        nome:
          type: string
          maxLength: 100
          example: Leonart Lima
        dataDaUltimaAlteracao:
          type: string
          maxLength: 20
          example: 2024-06-01T12:00:00
        dataDeCriacao:
          type: string
          maxLength: 20
          example: 2024-05-01T09:00:00
        endereco:
          type: string
          maxLength: 100
          example: Rua Exemplo, 123
      required:
        - login
        - email
        - senha
        - nome
        - dataDaUltimaAlteracao
        - dataDeCriacao
        - endereco
    UsuarioUpdate:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
        login:
          type: string
        endereco:
          type: string
    TrocaSenha:
      type: object
      properties:
        senhaAtual:
          type: string
        novaSenha:
          type: string